#!/bin/sh
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.
#
#   ----------------------------------------------------------------------
#
# File: install
#
# Last modified: 22/05-2015
#
# Description:
#   Installation file for Light Switch application
#
# Authors:
#   Lars Erik Midtsundstad Storbukås <larserik.storbukas@gmail.com>
#   Ole Eirik Heggelund <oeheggel@gmail.com>
#
# Website:
#   http://storbukas.no/lightswitch
#
# ----------------------------------------------------------------------

# variables
LOCATION = "/opt/lightswitch"
RUN_FILE = "lightswitch.sh"
SERVICE_DIR = "special-files/"
SERVICE_FILE = "lightswitch"
COMMAND = "sudo python /opt/lightswitch/lightswitch.py"

##############################################################################
# start script and make sure user is running as root

# startup message
echo "Starting Light Switch installation..."

# make sure script is being run as root
if [[ $EUID -ne 0 ]]; then
	echo "You must be a root user" 2>&1
	exit 1
fi

##############################################################################
# make sure correct packages are installed

PACKAGES="git-core python-dev python-pip"

apt-get update

echo "Installing required packages..."
for pkg in $PACKAGES; do
    if dpkg --get-selections | grep -q "^$pkg[[:space:]]*install$" >/dev/null; then
        echo "$pkg is already installed" 2>&1
    else
		if apt-get -qq install $pkg; then
			echo "Successfully installed $pkg"
		else
			echo -e "Error installing $pkg" 2>&1
		fi
    fi
done

# TODO: get wiringpi from drogon.net

##############################################################################
# copy packages to correct location /opt/lightswitch, and create locations

mkdir -p $LOCATION
cp -r ./* $LOCATION
cd $LOCATION

chmod +x $RUN_FILE

##############################################################################
# create service

cp $SERVICE_DIR+$SERVICE_FILE /etc/init.d/
chmod +x /etc/init.d/$SERVICE_FILE

# remove special-files directory
rm -rf /opt/lightswitch/special-files

##############################################################################
# add cron job

#write out current crontab
crontab -l > lightswitch

#echo new cron into cron file
echo "* * * * * $COMMAND" >> lightswitch

#install new cron file
crontab lightswitch
rm lightswitch

##############################################################################
# end of installation script

# finish up
echo "Installation was successful!"